apiVersion: v1
kind: Service
metadata:
  name: raffle-backend-service
  namespace: raffle-system
spec:
  type: ClusterIP
  selector:
    app: raffle-backend
  ports:
    - port: 5000
      targetPort: 5000
